# Generated by Django 3.0.3 on 2020-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='parent',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='fax',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.PositiveSmallIntegerField(max_length=11),
        ),
    ]
