# Generated by Django 3.0.3 on 2020-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_auto_20200328_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='fax',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
