# Generated by Django 3.0.3 on 2020-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
