# Generated by Django 3.0.3 on 2020-03-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_hotel_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='img',
        ),
        migrations.AddField(
            model_name='hotel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
