# Generated by Django 3.0.3 on 2020-03-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0009_auto_20200329_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='thumbnail',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
