# Generated by Django 3.0.3 on 2020-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0011_auto_20200329_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/null.jpg', upload_to='images'),
        ),
    ]
