# Generated by Django 3.0.3 on 2020-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0012_auto_20200329_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='detail',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='detail',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
