# Generated by Django 3.0.3 on 2020-04-04 21:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0013_auto_20200329_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
