# Generated by Django 3.0.3 on 2020-04-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0015_auto_20200409_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Accommodation',
        ),
    ]
