# Generated by Django 3.0.3 on 2020-05-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0017_auto_20200505_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(max_length=1),
        ),
    ]
