# Generated by Django 3.0.3 on 2020-05-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0020_auto_20200510_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
