# Generated by Django 3.0.3 on 2020-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0021_auto_20200510_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='False', max_length=10),
        ),
    ]
