# Generated by Django 3.0.3 on 2020-05-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0022_comment_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='star',
            field=models.IntegerField(blank=True, choices=[('0', '-'), ('1', '(1) *'), ('2', '(2) **'), ('3', '(3) ***'), ('4', '(4) ****'), ('5', '(5) *****')], max_length=1),
        ),
    ]
