# Generated by Django 3.0.3 on 2020-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0024_auto_20200518_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/null.jpg', upload_to='images/accommodations'),
        ),
    ]
