# Generated by Django 3.0.3 on 2020-04-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200405_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormMassage',
            new_name='ContactFormMessage',
        ),
    ]
