# Generated by Django 3.0.3 on 2020-04-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200405_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmessage',
            old_name='massage',
            new_name='message',
        ),
    ]
