# Generated by Django 3.0.3 on 2020-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200518_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='message',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
