# Generated by Django 3.0.3 on 2020-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200515_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('menu', 'menu'), ('blog', 'blog'), ('agent', 'agent'), ('duyuru', 'duyuru'), ('etkinlik', 'etkinlik')], max_length=10),
        ),
    ]
