# Generated by Django 3.0.3 on 2020-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_reservationroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
